#!/bin/bash

source $(readlink -f ${BASH_SOURCE[0]} | xargs dirname)/lib/common.sh

if [ "$1" = 'setup' ]
then
	log "This syntax is deprecated; use 'git fork setup' instead."
	git fork "${@}"
fi

SOURCE_REMOTE=$(git fork get upstream.remote)
TARGET_REMOTE=$(git fork get remote)

if [ "$SOURCE_REMOTE" = "$TARGET_REMOTE" ]
then
	abort "Upstream and fork are the same remote ('$SOURCE_REMOTE'). Nothing to sync."
fi

git remote-sync "$SOURCE_REMOTE" "$TARGET_REMOTE"
